const properties = PropertiesService.getScriptProperties().getProperties();


const contactRequestTest = "https://api.infusionsoft.com/crm/rest/v1/contacts/?limit=1000&offset=0&order=id";
//Requests
const contactRequest = "https://api.infusionsoft.com/crm/rest/v1/contacts?optional_properties=custom_fields";

const companiesRequest = "https://api.infusionsoft.com/crm/rest/v1/companies";
const usersRequest = "https://api.infusionsoft.com/crm/rest/v1/users";
const productsRequest = "https://api.infusionsoft.com/crm/rest/v1/products";
const emailsRequest = "https://api.infusionsoft.com/crm/rest/v1/emails";
const affiliatesRequest = "https://api.infusionsoft.com/crm/rest/v1/affiliates";


const getCustomFieldsRequest = "https://api.infusionsoft.com/crm/rest/v1/contacts/model";

const filteredContactsSheet =  SpreadsheetApp.getActiveSpreadsheet().getSheetByName("Contacts"); //filteredContacts given_name != null && tagApplied = CurrentBxGlobalMember
const taggedContactsSheet =  SpreadsheetApp.getActiveSpreadsheet().getSheetByName("Current Bx Global Member"); //tagApplied = CurrentBxGlobalMember
const contactsSheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("contactsDump");


const companiesSheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("companies");
const usersSheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("users");
const productsSheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("products");
const emailsSheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("emails");
const affiliatesSheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("affiliates");
const customFieldsSheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("customFields");
const calculations = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("Calculations");
const calLocAustralia = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("Australia");
const calLocUSA = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("USA");

const extraSheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("extraSheet");


const tagCurrentBxGlobalMemeber = {
  baltic: YOUR_BALTIC_TAG_ID,
  canada: YOUR_CANADA_TAG_ID,
  newZealand: YOUR_NEW_ZEALAND_TAG_ID,
  usa: YOUR_USA_TAG_ID
}



const australiaLocations = [
"",
"Canberra Central",
"Canberra North Lunch",
"Queanbeyan",
"",
"",
"",
"",
"",
"Campbelltown",
"",
"",
"Parramatta",
"Sydney Hills",
"",
"",
"Penrith",
"",
"",
"",
"",
"Cronulla Lunch",
"St George",
"Sutherland",
"Wollongong",
"",
"",
"",
"",
"",
"Sydney CBD",
"Alexandria",
"Bondi Beach",
"Sydney CBD Lunch",
"Inner West",
"",
"",
"North Sydney",
"Manly",
"Hornsby",
"Crows Nest Lunch",
"",
"",
"",
"",
"Newcastle",
"Gosford",
"",
"",
"",
"",
"",
"",
"",
"Gold Coast (Burleigh Heads)",
"Surfers Paradise",
"Robina",
"Varsity",
"Southport Lunch",
"Coomera",
"Palm Beach",
"",
"Gold Coast Dinner",
"Helensvale",
"",
"",
"",
"",
"",
"",
"",
"Brisbane CBD",
"South Brisbane",
"Chermside",
"Mt Gravatt",
"East Brisbane",
"North Lakes",
"Springwood",
"Capalaba Lunch",
"Ipswich",
"Toowoomba",
"Redcliffe",
"",
"",
"",
"",
"Sunshine Coast",
"Sunshine Coast South",
"Noosa",
"Mackay Lunch",
"",
"",
"",
"",
"",
"",
"",
"North Adelaide",
"Glenelg Lunch",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Fremantle Lunch",
"South Perth",
"Perth Central",
"City Beach",
"Joondalup",
"Perth South",
"",
"",
"",
"",
"",
"",
"",
"East Melbourne",
"South Melbourne",
"West Melbourne Lunch",
"Brighton",
"Dandenong",
"Mount Waverley",
"Tullamarine",
"Geelong",
"Epping",
"Doncaster",
"",
"",
"",
"",
"",
"",
"North Hobart",
"Hobart Central Lunch",
"South Hobart",
"Launceston",
"Devonport",
"",
"",
"",
"",
"",
""
]

const usaLocations = [
  "",
"",
"",
"Round Rock",
"South Austin",
"Cedar Park Lunch",
"North Austin Lunch",
"Georgetown",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Northwest San Antonio",
"North Central San Antonio",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Troy Lunch",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
]

